"""add is_homepage and site_config

Revision ID: 8cceb6680e64
Revises: 7f5aac9a1e40
Create Date: 2026-06-09 14:14:12.475159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cceb6680e64'
down_revision: Union[str, Sequence[str], None] = '7f5aac9a1e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homepage_rotation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pets', sa.Column('is_homepage', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'is_homepage')
    op.drop_table('site_config')
    # ### end Alembic commands ###
